### ISSUE TITLE
Meta viewport for Sketchbot

### ISSUE THREAD

**Issue by michaelsanford** [googlearchive/ChromeWebLab#65]
Markup and styling
- [x] Add meta viewport definition (see #51).
- [x] Fix CSS as a consequence of above.
- [ ] Ensure scripts pulled in #63 (bbab7cf and 59ad9a4) are beautified.

(I'm happy to take this one.)

**Comment by PaulKinlan** [comment]
Awesome.  thanks.
